In [5]:
import pandas as pd
import numpy as np

In [3]:
!ls

Inventario300426.xlsx  Inventario300426.xlsx:Zone.Identifier  Untitled.ipynb

In [6]:
df = pd.read_excel('Inventario300426.xlsx')
df

,Código,Descripción,Familia,Pres.,Situación,S.Actual,S.Minimo,S.Maximo,P.v.p.,P.m.c.,...,Dias de Cobertura,Uds.Vendidas,Tot.Venta,Caducidad,U.Entrada,U.Salida,G.Terap.,Grupo Terapeútico,C.Labor.,Laboratorio
0,0.0,HOLORAM,BOTIQUIN,***,NaN,0,0,0,121.98,92.64,...,NaN,NaN,NaN,NaN,03/03/23,03/03/23,NaN,NaN,NaN,NaN
1,1.0,MEDALLON FLOR DE LA VIDA,ORTOPEDIA Y PIES,***,NaN,0,0,0,3.12,14.00,...,NaN,NaN,NaN,NaN,NaN,20/01/16,NaN,NaN,NaN,NaN
2,12.0,EDENSAN 01 HELP,DIETETICA Y HERBORISTERIA,***,NaN,0,0,0,3.75,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00002,roandiet
3,26.0,HEPAPRAX 100 COMP.,HOMEOPATÍA,***,NaN,0,0,0,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E1126,PRAXIS PHARMACEUTICAL SA
4,29.0,EDESAN 02 SOM 20 BOLSITAS,DIETETICA Y HERBORISTERIA,***,NaN,0,0,0,4.00,0.00,...,NaN,NaN,NaN,NaN,NaN,20/04/12,NaN,NaN,00002,roandiet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29701,660083.2,ONDANSETRON NORMON EFG 4 MG 15 COMPRIMIDOS RECUB,ESPECIALIDAD,COM,NaN,0,0,0,33.31,22.30,...,0.0,1.0,33.31,NaN,13/04/26,14/04/26,A04AA,ANTAGONISTAS DE RECEPTORES DE SEROTONINA (5-HT3),E0426,NORMON
29702,660439.7,CIALIS DIARIO 5 MG 28 COMPRIMIDOS,ESPECIALIDAD,COM,NaN,1,0,0,134.35,91.51,...,120.0,1.0,134.35,30/09/28,28/04/26,21/04/26,G04BE,FARMACOS USADOS EN DISFUNCION ERECTIL,E0346,LILLY
29703,661598.0,IRBESARTAN CINFA EFG 150 MG 28 COMPRIMIDOS,ESPECIALIDAD,COM,NaN,1,0,1,7.74,5.61,...,30.0,4.0,30.96,31/01/29,27/04/26,27/04/26,C09CA,ANTAGONISTAS DE LOS RECEPTORES DE ANGIOTENSINA...,E0111,CINFA
29704,661872.1,CRESTOR 10 MG 28 COMPRIMIDOS RECUBIERTOS,ESPECIALIDAD,COM,NaN,3,0,1,9.52,6.42,...,72.0,5.0,47.60,01/11/27,03/03/26,24/03/26,C10AA,INHIBIDORES DE LA HMG COA REDUCTASA,E0267,ASTRAZENECA FARMACEUTICA SPAIN
29705,665299.2,MICRALAX EMULSION RECTAL 12 MICROENEMAS 5 ML,EFP,NaN,NaN,1,0,1,18.95,12.17,...,40.0,3.0,55.85,01/12/30,07/04/26,06/04/26,A06AG,ENEMAS,E0763,PFIZER CONSUMER HEALTHCARE

In [13]:
df['Familia'].unique()

array(['BOTIQUIN', 'ORTOPEDIA Y PIES', 'DIETETICA Y HERBORISTERIA',
       'HOMEOPATÍA', 'ALIMENTACIÓN INFANTIL', 'COSMÉTICA', 'H. INFANTIL',
       'SALUD SEXUAL', 'CORPORAL', 'CABELLO', 'OPTICA',
       'PRODUCTOS INFANTILES', 'VETERINARIA', 'BUCAL',
       'FORMULAS MAGISTRALES', 'ESPECIALIDAD', 'ESPACIALIDADES MAS 143',
       'EFP', 'SOLARES', nan], dtype=object)

In [33]:
df.columns

Index(['Código', 'Descripción', 'Familia', 'Pres.', 'Situación', 'S.Actual',
       'S.Minimo', 'S.Maximo', 'P.v.p.', 'P.m.c.', 'P.u.c.', 'Valor a Pvp',
       'Valor a Pmc', 'Valor a Puc', '%Margen a Pmc', '%Margen a Puc',
       'Rotación', 'Dias de Cobertura', 'Uds.Vendidas', 'Tot.Venta',
       'Caducidad', 'U.Entrada', 'U.Salida', 'G.Terap.', 'Grupo Terapeútico',
       'C.Labor.', 'Laboratorio'],
      dtype='object')

# Caducidad

In [37]:
interes_caducidad=['Código', 'Descripción', 'Familia','S.Actual','S.Minimo', 'S.Maximo','Rotación','Caducidad']

In [41]:
#Quitamos los valores desconocidos de Caducidad y los rellenamos con unknown
df_caducidad = df[interes_caducidad]
df_caducidad['Caducidad'].fillna('Unknown', inplace=True)

/tmp/ipykernel_2869/2051004669.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_caducidad['Caducidad'].fillna('Unknown', inplace=True)
/tmp/ipykernel_2869/2051004669.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_caducidad['Caducidad'].fillna('Unknown', inplace=True)

In [45]:
#Quitamos los valores desconocidos pues no nos interesan para este fin 
df_caducidad_act = df_caducidad[df_caducidad['Caducidad']!='Unknown']

In [65]:
#Cambiamos formato para que sea de fecha y creamos una copia con lo nuevo
df_caducidad_act['Caducidad_act'] = pd.to_datetime(df_caducidad_act['Caducidad'], format="%d/%m/%y", yearfirst=False)

/tmp/ipykernel_2869/230633024.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_caducidad_act['Caducidad_act'] = pd.to_datetime(df_caducidad_act['Caducidad'], format="%d/%m/%y", yearfirst=False)

In [66]:
df_caducidad_act

,Código,Descripción,Familia,S.Actual,S.Minimo,S.Maximo,Rotación,Caducidad,Caducidad_act
23,1002.0,DROSERA N 64,HOMEOPATÍA,1,0,0,NaN,01/07/29,2029-07-01
28,1021.0,KLEENEX BOLSILLO INTERHAPOTEK,BOTIQUIN,218,0,0,0.53,01/01/29,2029-01-01
68,2518.0,FARMAVITAL ESENCIA CITRONELLA,DIETETICA Y HERBORISTERIA,0,0,0,0.00,01/09/15,2015-09-01
70,2521.0,FARMAVITAL ESENCIA SALVIA,DIETETICA Y HERBORISTERIA,0,0,0,0.00,01/09/15,2015-09-01
85,2738.0,PROPOLI PLUS EPID 10 STICK SPECCHIASOL,DIETETICA Y HERBORISTERIA,0,0,0,0.00,01/11/18,2018-11-01
...,...,...,...,...,...,...,...,...,...
29700,659529.9,LOSARTAN/HIDROCLOROTIAZIDA STADA EFG 50/12.5 MG,ESPECIALIDAD,2,0,2,2.00,31/05/28,2028-05-31
29702,660439.7,CIALIS DIARIO 5 MG 28 COMPRIMIDOS,ESPECIALIDAD,1,0,0,1.00,30/09/28,2028-09-30
29703,661598.0,IRBESARTAN CINFA EFG 150 MG 28 COMPRIMIDOS,ESPECIALIDAD,1,0,1,4.00,31/01/29,2029-01-31
29704,661872.1,CRESTOR 10 MG 28 COMPRIMIDOS RECUBIERTOS,ESPECIALIDAD,3,0,1,1.67,01/11/27,2027-11-01
29705,665299.2,MICRALAX EMULSION RECTAL 12 MICROENEMAS 5 ML,EFP,1,0,1,2.95,01/12/30,2030-12-01

## Productos ya caducados 
- Vamos a explorar productos que ya esten caducados , a partir de la fecha que sea menor que la de hoy 
- Exploramos que el stock actual S.Actual > 0 ya que esos son los productos que tenemos en la farmacia

In [69]:

df_productos_caducados = df_caducidad_act[(df_caducidad_act['Caducidad_act'] < pd.Timestamp.today()) & (df['S.Actual']>0)]
df_productos_caducados

/tmp/ipykernel_2869/46530863.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_productos_caducados = df_caducidad_act[(df_caducidad_act['Caducidad_act'] < pd.Timestamp.today()) & (df['S.Actual']>0)]

,Código,Descripción,Familia,S.Actual,S.Minimo,S.Maximo,Rotación,Caducidad,Caducidad_act
226,823971.9,NUVARING 0.12/0.015 MG/24 H 1 ANILLO VAGINAL,ESPECIALIDAD,2,0,2,3.50,30/04/26,2026-04-30
4061,179092.7,PERSPIREX COMFORT ANTITRANSPIRANTE 1 ROLL ON 20,CORPORAL,3,0,0,NaN,01/01/25,2025-01-01
4957,197177.7,"ESPARADRAPO FIXOTAPE PORE PAPEL 1 UNIDAD 9,14 M",BOTIQUIN,1,0,0,NaN,01/01/25,2025-01-01
5424,206170.5,HELIOCARE 360º MD A-R EMULSION PROTECTOR SOLAR P,SOLARES,2,0,1,0.50,01/01/26,2026-01-01
6209,260083.6,LACER OROS COLUTORIO 500 ML,BUCAL,1,0,1,2.00,09/02/08,2008-02-09
8342,499994.5,SORIA NATURAL GINKGO EXTRACTO,DIETETICA Y HERBORISTERIA,1,0,1,NaN,01/08/25,2025-08-01
9434,656069.3,LAMOTRIGINA STADA EFG 200 MG 30 COMPRIMIDOS DISP,ESPECIALIDAD,1,0,1,NaN,30/06/25,2025-06-30
10000,663333.5,INVEGA 3 MG 28 COMPRIMIDOS LIBERACION PROLONGADA,ESPECIALIDAD,1,0,0,NaN,01/08/20,2020-08-01
10289,671388.4,YASMIN 0.03/3 MG 3 X 21 COMPRIMIDOS RECUBIERTOS,ESPECIALIDAD,1,0,1,NaN,30/06/24,2024-06-30
10392,672977.9,SIMVASTATINA UXA EFG 10 MG 28 COMPRIMIDOS RECUBI,ESPECIALIDAD,1,0,0,NaN,31/01/23,2023-01-31
10635,682538.9,ARKOCAPSULAS CASTAÑO DE INDIAS 275 MG 48 CAPSULA,DIETETICA Y HERBORISTERIA,1,0,1,NaN,01/03/22,2022-03-01
10874,692160.9,EVOPAD 50 MCG/24 H 8 PARCHES TRANSDERMICOS 3.2 M,ESPECIALIDAD,1,0,1,3.00,29/02/24,2024-02-29
10923,694030.3,KEFLORIDINA FORTE 500 MG 28 CAPSULAS,ESPECIALIDAD,1,0,0,NaN,01/04/24,2024-04-01
11091,697797.2,LEVONORGESTREL/ETINILESTRADIOL STADA GENERIC EFG,ESPECIALIDAD,2,0,0,NaN,31/01/25,2025-01-31
12011,730308.4,DELTIUS 50.000 UI 2 CAPSULAS,ESPECIALIDAD,1,0,1,1.00,30/09/25,2025-09-30
12729,817737.0,BIARRITZ SOINBEBE LINIMENTO OLEO CALCAREO,COSMÉTICA,1,0,0,NaN,01/01/26,2026-01-01
13637,899989.7,NATURCOSMETIKA CHAMPU TRATANTE ALOE/AVENA 740,COSMÉTICA,2,0,1,NaN,01/01/25,2025-01-01
14056,980706.1,PARACETAMOL WINTHROP 500 MG 20 COMPRIMIDOS,ESPECIALIDAD,1,0,0,NaN,01/12/21,2021-12-01
14282,10189.0,ESI ALOE VERA GEL/ARBOL TE 100ML,DIETETICA Y HERBORISTERIA,1,0,0,NaN,01/10/25,2025-10-01
15673,199902.3,APIVITA EXPRESS REVITALIZANTE NARANJA,COSMÉTICA,1,0,0,2.00,01/01/26,2026-01-01
15674,199902.3,APIVITA EXPRESS REVITALIZANTE NARANJA,COSMÉTICA,1,0,0,2.00,01/01/26,2026-01-01
16334,151318.2,VP TERMOMETRO DIGITAL FLEXIBLE,BOTIQUIN,4,0,0,NaN,01/01/25,2025-01-01
19670,181598.9,GINECANESCALM GEL CREMA 15 G,ESPECIALIDAD,1,0,0,NaN,01/09/25,2025-09-01
19810,895898.6,ESI PROPOLAID JENGIBRE/ERISIMO 30 TABLETAS,DIETETICA Y HERBORISTERIA,2,0,0,NaN,01/11/25,2025-11-01
20035,185173.4,BLEMIL 2 PLUS FORTE 800 G,DIETETICA Y HERBORISTERIA,1,0,0,NaN,01/08/25,2025-08-01
21293,348001.7,PROTECTOR DE CAMA AMD PAD EXTRA 60 X 40 14 U,SALUD SEXUAL,5,0,1,NaN,01/01/25,2025-01-01
21575,377044.6,SAUGELLA ATTIVA 250 ML.,SALUD SEXUAL,1,0,1,NaN,01/01/21,2021-01-01
22487,519567.4,PRANAROM HERBAL CONSUELDA MAYOR BÁLSAMO,DIETETICA Y HERBORISTERIA,1,0,0,1.00,01/01/26,2026-01-01
22488,519567.4,PRANAROM HERBAL CONSUELDA MAYOR BÁLSAMO,DIETETICA Y HERBORISTERIA,1,0,0,1.00,01/01/26,2026-01-01
22508,524523.2,PRANAROM ROMERO ALCANFOR A.E,DIETETICA Y HERBORISTERIA,1,0,1,NaN,01/01/24,2024-01-01
22509,524523.2,PRANAROM ROMERO ALCANFOR A.E,DIETETICA Y HERBORISTERIA,1,0,1,NaN,01/01/24,2024-01-01
22676,597527.6,PRANAROM ACEITE ESENCIAL DE MANDARINA,DIETETICA Y HERBORISTERIA,1,0,1,NaN,01/09/21,2021-09-01
22677,597527.6,PRANAROM ACEITE ESENCIAL DE MANDARINA,DIETETICA Y HERBORISTERIA,1,0,1,NaN,01/09/21,2021-09-01
22884,651231.9,ELECOR 25 MG 30 COMPRIMIDOS RECUBIERTOS,ESPECIALIDAD,1,0,1,NaN,30/11/25,2025-11-30
23417,659397.4,MIRTAZAPINA FLAS STADA EFG 15 MG 30 COMPRIMIDOS,ESPECIALIDAD,2,0,1,1.00,31/03/26,2026-03-31
24212,679946.8,TEGRETOL 200 MG 100 COMPRIMIDOS (BLISTER AL/PVC/,ESPECIALIDAD,1,0,0,2.00,31/03/22,2022-03-31
24298,683802.0,ARKOCAPSULAS RUSCO 350 MG 48 CAPSULAS,DIETETICA Y HERBORISTERIA,1,0,1,NaN,01/01/23,2023-01-01
24322,686770.9,BUDESONIDA PULMICTAN 200 MCG/PULSACION 1 AEROSOL,ESPECIALIDAD,1,0,1,2.00,31/12/25,2025-12-31
24361,688033.3,IBEROGAST GOTAS ORALES SOLUCION 50 ML,ESPECIALIDAD,1,0,1,2.00,01/05/26,2026-05-01
25147,724309.0,ATORVASTATINA STADAGEN EFG 40 MG 28 COMPRIMIDOS,ESPECIALIDAD,7,0,1,3.57,30/09/25,2025-09-30
25825,850560.9,ENALAPRIL STADA EFG 20 MG 28 COMPRIMIDOS,ESPECIALIDAD,4,2,4,6.00,31/10/25,2025-10-31
26072,899505.9,ARGENTUM BERBERIS COMPOSITUM 60 ML,HOMEOPATÍA,1,0,0,NaN,01/05/21,2021-05-01
26089,899545.5,POTITO YAMMY PERA+KIWI+AGUACATE,ALIMENTACIÓN INFANTIL,1,0,0,NaN,01/05/09,2009-05-01
26305,899953.8,BIARRITZ SPRAY SOLAR INFANTIL 50+ 150 ML,SOLARES,2,0,1,NaN,01/01/26,2026-01-01
26708,987986.0,ENERGY EXTREME 16 CPS NATYSAL,DIETETICA Y HERBORISTERIA,2,0,0,NaN,01/02/25,2025-02-01
27035,220916.9,COMPRESA INCONTINENCIA ORINA LEVES APOSAN MUJER,SALUD SEXUAL,1,0,1,NaN,01/01/25,2025-01-01
28044,694701.2,AMOXICILINA/ACIDO CLAVULANICO ARDINECLAV EFG 875,ESPECIALIDAD,1,0,1,NaN,01/09/21,2021-09-01
28874,703789.7,AMOXICILINA/ACIDO CLAVULANICO STADA EFG 875/125,ESPECIALIDAD,2,0,1,2.57,31/03/26,2026-03-31
29317,710313.4,ATORVASTATINA STADAGEN EFG 80 MG 28 COMPRIMIDOS,ESPECIALIDAD,2,0,0,0.50,31/12/24,2024-12-31
29447,863167.4,URBASON 16 MG 30 COMPRIMIDOS,ESPECIALIDAD,1,0,1,1.00,31/10/25,2025-10-31

## Caducidad de 2026
1. Obtenemos el año actual 
2. Vemos productos que tenemos en Stock , S.Actual > 0
3. Vemos productos cuyo año es el que queremos (año actual)

In [97]:
año_actual = pd.Timestamp.today().year
df_productos_van_caducar = df_caducidad_act[(df_caducidad_act['Caducidad_act'].dt.year == año_actual) & (df['S.Actual']>0)]
df_productos_van_caducar.sort_values('Caducidad_act', ascending = True, inplace= True)

/tmp/ipykernel_2869/172867871.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_productos_van_caducar = df_caducidad_act[(df_caducidad_act['Caducidad_act'].dt.year == año_actual) & (df['S.Actual']>0)]
/tmp/ipykernel_2869/172867871.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_productos_van_caducar.sort_values('Caducidad_act', ascending = True, inplace= True)

# STOCK  
La rotación debe ser mayor que 0 pues esto indica que el producto es de interes y se vende , para el aviso de stock necesitamos 
1. Que la Rotacion sea mayor que 0 
2. Que los productos sean de las familias de interes

In [73]:
familias_interes=['DIETETICA Y HERBORISTERIA','SOLARES','COSMÉTICA','CORPORAL']
interes_caducidad

['Código',
 'Descripción',
 'Familia',
 'S.Actual',
 'S.Minimo',
 'S.Maximo',
 'Rotación',
 'Caducidad']

In [75]:
df_interes_stock = df[df['Familia'].isin(familias_interes) & df['Rotación']>0 ][interes_caducidad]
df_interes_stock

,Código,Descripción,Familia,S.Actual,S.Minimo,S.Maximo,Rotación,Caducidad
20,265.0,ABEÑULA BLANCA GRANDE,COSMÉTICA,1,0,1,1.00,NaN
146,5900.0,EUCERIN PACK MANOS UREA,CORPORAL,3,0,0,0.24,01/02/28
185,192584.8,LETIAT4 HIDROGEL ANTI-PICOR 1 ENVASE 50 ML,CORPORAL,1,0,1,1.00,01/03/28
186,192592.3,GELSECTAN 15 CAPSULAS,DIETETICA Y HERBORISTERIA,1,0,1,4.00,30/07/27
207,823175.1,SUPERLATIVA MAGNESIUM 60 CAPS,DIETETICA Y HERBORISTERIA,5,0,0,0.20,01/02/28
...,...,...,...,...,...,...,...,...
29674,514821.2,PRANAROM AROMAFORCE SPRAY PURIFICANTE,DIETETICA Y HERBORISTERIA,5,0,1,0.76,01/01/31
29675,515774.0,PRANAROM UNGUENTO RESPIRAZINE CON EUCALIPTO,DIETETICA Y HERBORISTERIA,6,0,1,1.37,01/01/28
29676,515774.0,PRANAROM UNGUENTO RESPIRAZINE CON EUCALIPTO,DIETETICA Y HERBORISTERIA,6,0,1,1.37,01/01/28
29678,568909.8,PRANAROM ACEITE ESENCIAL DE NARANJA DULCE,DIETETICA Y HERBORISTERIA,1,0,1,1.00,01/04/28
29679,568909.8,PRANAROM ACEITE ESENCIAL DE NARANJA DULCE,DIETETICA Y HERBORISTERIA,1,0,1,1.00,01/04/28

In [83]:
df_interes_stock_stock_caducidad = df_interes_stock[df_interes_stock['Caducidad'].isna()]
df_interes_stock_stock_caducidad

,Código,Descripción,Familia,S.Actual,S.Minimo,S.Maximo,Rotación,Caducidad
20,265.0,ABEÑULA BLANCA GRANDE,COSMÉTICA,1,0,1,1.00,NaN
1909,152288.7,BIMANAN BARRITAS CHOCOLATE CRU 35 G 1 U (EXP 24,DIETETICA Y HERBORISTERIA,4,0,0,0.25,NaN
1948,152741.7,XHEKPON CREMA CONTORNO 15ML,COSMÉTICA,1,0,1,1.00,NaN
2497,159078.7,DEXERYL CREMA PROTECCION CUTANEA DUCRAY 500 ML,CORPORAL,2,0,0,1.50,NaN
3498,171072.7,KLORANE CHAMPU SECO A LA LECHE DE AVENA CABELLO,COSMÉTICA,1,0,1,1.00,NaN
4535,187424.5,GASA A`PSAM TMT 10 10 20 20 UNIDADES,DIETETICA Y HERBORISTERIA,1,0,1,1.00,NaN
4703,191039.4,FARLINE SWEETSIN CARAMELOS HIERBAS SUIZAS 1 BOLS,DIETETICA Y HERBORISTERIA,2,0,0,3.50,NaN
4966,197242.2,EUCERIN HYALURON FILLER+ ELASTICITY DIA FPS 30 1,COSMÉTICA,1,0,0,1.00,NaN
5462,207136.0,FARLINE CREMA PIES 30% UREA 1 TUBO 150 ML,CORPORAL,1,0,1,2.18,NaN
5588,210443.3,ISDINDEO NATURE 24H ISDIN,CORPORAL,1,0,1,3.00,NaN
5631,212154.6,AGUA TERMAL DE URIAGE 50 ML,CORPORAL,3,0,3,0.34,NaN
5941,242776.1,"PINZAS DEPILAR BETER CROMADA P RECTA 7,2 CM",COSMÉTICA,1,0,1,1.00,NaN
7074,341533.0,DESODORANTE SIN SALES DE ALUMI 50 ML,CORPORAL,1,0,1,1.00,NaN
7233,353565.6,VICHY HOMME DESODORANTE PIELES SENSIBLES BOLA S.,CORPORAL,1,0,1,14.00,NaN
7624,391649.3,JABON GRISI NEUTRO 100 G,CORPORAL,1,0,1,6.00,NaN
13469,899672.8,PRANAROM BALSAMO PECTORAL,CORPORAL,3,0,0,1.33,NaN
13470,899672.8,PRANAROM BALSAMO PECTORAL,CORPORAL,3,0,0,1.33,NaN
14482,349.0,ABEÑULA NE GD,COSMÉTICA,1,0,1,0.95,NaN
14559,202350.5,FARLINE GEL DE DUCHA EXFOLIANTE 1 TUBO 200 ML,CORPORAL,1,0,1,1.00,NaN
14857,182918.4,SENSIBIO GEL MOUSSANT BIODERMA 200 ML,COSMÉTICA,1,0,1,2.00,NaN
16266,151130.0,MELA B3 SERUM 1 FRASCO 30 ML,COSMÉTICA,1,0,1,0.95,NaN
16459,843702.3,SNACK DE PAVO DE CORRAL SALMON FRUTA 120 GRA,SOLARES,12,0,0,0.25,NaN
16917,157816.7,PURETE THERMALE DESMAQUILLANTE OJOS ANTICAIDA PE,COSMÉTICA,1,0,1,5.00,NaN
17658,205300.7,ARKOCAPSULAS ASHWAGANDHA BIO 45 CAPSULAS,DIETETICA Y HERBORISTERIA,1,0,1,1.00,NaN
18474,169130.9,MULTICENTRUM MUJER 50+ 30 COMPRIMIDOS,DIETETICA Y HERBORISTERIA,2,0,1,1.00,NaN
18648,170688.1,VICHY DESODORANTE REGULADOR SPRAY 125 ML.,CORPORAL,1,0,1,4.97,NaN
18688,171100.7,IAP PHARMA POUR FEMME Nº 16 150 ML,COSMÉTICA,1,0,0,1.00,NaN
19212,173189.0,MULTICENTRUM MUJER 50+ 90 COMP,DIETETICA Y HERBORISTERIA,1,0,1,1.00,NaN
19259,174108.0,NEUTROGENA MANOS V.R. SPF25 CREMA 75 ML,COSMÉTICA,1,0,0,1.00,NaN
19357,175668.8,EUDERMIN TALCO 200 G,CORPORAL,1,0,1,3.00,NaN
19992,184310.4,SEBIUM SENSITIVE BIODERMA 30 ML,COSMÉTICA,1,0,1,1.00,NaN
20246,9184.0,FARLINE PACK AGUA MICELAR 500ML+ 100ML,COSMÉTICA,1,0,1,0.94,NaN
20694,26808.0,FARLINE TRIPLO GEL ZERO 1L 1U,CORPORAL,1,0,1,3.00,NaN
20910,316729.1,LETIBALM 10 ML.,COSMÉTICA,1,0,1,5.96,NaN
20911,316729.1,LETIBALM 10 ML.,COSMÉTICA,1,0,1,5.96,NaN
21680,385278.4,GENOCUTAN 1000 ML,CORPORAL,1,0,1,2.00,NaN
21901,422828.1,PALO SANTO,DIETETICA Y HERBORISTERIA,2,0,0,4.00,NaN
22363,502424.0,PRANAROM DIGEST CONFORT 21 PASTILLAS,DIETETICA Y HERBORISTERIA,1,0,1,2.00,NaN
22485,519154.6,PRANAROM AROMALGIC ROLL ON ARTICULACIONES,DIETETICA Y HERBORISTERIA,5,0,0,0.20,NaN
22486,519154.6,PRANAROM AROMALGIC ROLL ON ARTICULACIONES,DIETETICA Y HERBORISTERIA,5,0,0,0.20,NaN
26537,954269.6,PRANAROM ACEITE VEGETAL DE ARNICA 50 ML,DIETETICA Y HERBORISTERIA,1,0,0,2.00,NaN
27201,238444.6,PROTECTOR LABIAL EUCERIN PIEL SENSIBLE 4.8 G,COSMÉTICA,4,0,0,5.25,NaN
28329,213550.5,FARLINE TOALLITAS DESMAQUILLANTES 25 UNIDADES,CORPORAL,1,0,3,3.67,NaN
28693,212794.4,AROMAFLEX FORTE 30 COMPRIMIDOS,DIETETICA Y HERBORISTERIA,1,0,1,2.00,NaN
28694,212794.4,AROMAFLEX FORTE 30 COMPRIMIDOS,DIETETICA Y HERBORISTERIA,1,0,1,2.00,NaN
28970,251197.2,ARNIDOL GEL STICK 15 ML,CORPORAL,1,0,1,3.97,NaN
28996,304394.6,AVENE AGUA TERMAL 150ML,COSMÉTICA,1,0,1,1.06,NaN
29089,163521.1,JUANOLA PASTILLAS BLANDAS PROPOLIS MIEL VIT C AL,DIETETICA Y HERBORISTERIA,1,0,1,4.00,NaN
29125,171692.7,IAP PHARMA POUR FEMME Nº 21 150 ML,COSMÉTICA,2,0,0,1.00,NaN
29135,211838.6,MULTICENTRUM HOMBRE 90 COMPRIMIDOS,DIETETICA Y HERBORISTERIA,1,0,0,1.00,NaN
29141,173399.3,RICOLA CARAMELOS SIN AZUCAR NARANJA 50 G,DIETETICA Y HERBORISTERIA,1,0,1,1.00,NaN
29416,899518.9,APIVITA OILY DANDRUFF CHAMPU CASPA GRASA 250ML,COSMÉTICA,1,0,1,1.00,NaN
29417,899518.9,APIVITA OILY DANDRUFF CHAMPU CASPA GRASA 250ML,COSMÉTICA,1,0,1,1.00,NaN
29418,899524.0,APIVITA MASCARILLA EXPRESS ARCILLA VERDE,COSMÉTICA,2,0,0,0.50,NaN
29419,899524.0,APIVITA MASCARILLA EXPRESS ARCILLA VERDE,COSMÉTICA,2,0,0,0.50,NaN
29475,13787.0,FARLINE DESODORANTE TAPA AZUL,COSMÉTICA,1,0,1,3.37,NaN
29528,163411.5,VICHY STRESS RESIST TTO INTENS ANTITRANSP 72H,CORPORAL,1,0,1,11.97,NaN
29566,187651.5,CERAVE GEL LIMPIADOR ESPUMOSO 236 ML,COSMÉTICA,1,0,1,3.94,NaN

In [85]:
df_familias_interess_sin_rotacion = df[df['Familia'].isin(familias_interes) & (df['S.Actual']!=0) & (df['Rotación']==0 | df['Rotación'].isna()) ][interes_caducidad]

In [99]:
with pd.ExcelWriter('reportes1.xlsx', engine='openpyxl') as writer:
    df_productos_caducados.to_excel(writer, sheet_name='Caducados', index=False)
    df_productos_van_caducar.to_excel(writer, sheet_name='Caducan 26', index=False)
    df_interes_stock_stock_caducidad.to_excel(writer, sheet_name='stock sin caducidad', index=False)
    df_familias_interess_sin_rotacion.to_excel(writer, sheet_name='stock sin rotacion', index=False)

In [94]:
df_productos_caducados.to_excel('caducados.xlsx', index=False)

/tmp/ipykernel_2869/3656596605.py:1: UserWarning: Pandas requires version '3.0.5' or newer of 'xlsxwriter' (version '3.0.3' currently installed).
  df_productos_caducados.to_excel('caducados.xlsx', index=False)

In [93]:
!pip install --upgrade XlsxWriter
!pip install --upgrade pip

Requirement already satisfied: XlsxWriter in /home/andreamegias/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages (3.2.9)

# STOCK TOTAL

In [102]:
df_total = df[interes_caducidad].copy()

In [103]:
df_total.head(2)

,Código,Descripción,Familia,S.Actual,S.Minimo,S.Maximo,Rotación,Caducidad
0,0.0,HOLORAM,BOTIQUIN,0,0,0,0.0,NaN
1,1.0,MEDALLON FLOR DE LA VIDA,ORTOPEDIA Y PIES,0,0,0,0.0,NaN

In [105]:
df_total[(df_total['Rotación']==0) & (df_total['S.Actual']!=0)]

,Código,Descripción,Familia,S.Actual,S.Minimo,S.Maximo,Rotación,Caducidad
3187,167348.0,VITACRECIL COMPLEX FORTE CAPS 90 CAPSULAS,DIETETICA Y HERBORISTERIA,1,0,0,0.0,01/06/28
3591,172270.6,PANTY COMP NORMAL 140 DEN VARISAN BEIGE CALIBRAD,ORTOPEDIA Y PIES,1,0,0,0.0,NaN
4059,179086.6,RILASTIL CUMLAUDE LAB: PREBIOTIC 10 OVULOS VAGIN,SALUD SEXUAL,1,0,1,0.0,NaN
4531,187397.2,FARLINE GEL PIERNAS CANSADAS 1 ENVASE 200 ML,ORTOPEDIA Y PIES,9,0,1,0.0,01/01/28
13931,961806.3,THERASCIENCE PHYSIOMANCE DETOX 40 COMPRIM,DIETETICA Y HERBORISTERIA,1,0,0,0.0,01/01/28
16463,843720.7,NUTRINAT PEA OPTIM 20 CAPS,DIETETICA Y HERBORISTERIA,2,0,0,0.0,01/07/26
18094,100242.0,DIGESTOGREEN SOL ORAL 50ML DRASANVI,VETERINARIA,1,0,0,0.0,NaN
19937,183352.5,SLEEPEEL GOTAS 30 ML,DIETETICA Y HERBORISTERIA,1,0,0,0.0,NaN
19938,183352.5,SLEEPEEL GOTAS 30 ML,DIETETICA Y HERBORISTERIA,1,0,0,0.0,NaN
22217,500000.8,BOTIQUIN,BOTIQUIN,1,0,0,0.0,NaN
24514,693796.9,MASTICAL 1250 MG (500 MG CA) 60 COMPRIMIDOS MAST,ESPECIALIDAD,1,0,1,0.0,NaN
26652,975060.2,XALACOM 0.05/5 MG/ML COLIRIO 1 FRASCO SOLUCION 2,ESPECIALIDAD,1,0,0,0.0,29/02/28
28750,219703.9,TUBO DE GEL RECUBIERTO ELASTICO VP NATURA FOOT C,ORTOPEDIA Y PIES,4,0,0,0.0,01/01/28
29085,161563.3,JUANOLA PASTILLAS BLANDAS PROPOLIS + MIEL Y ZINC,DIETETICA Y HERBORISTERIA,1,0,1,0.0,NaN
29402,843094.9,CITALOPRAM KERN PHARMA EFG 20 MG 28 COMPRIMIDOS,ESPECIALIDAD,1,0,0,0.0,NaN

In [108]:
df_total_sin_caducidad = df_total[(df_total['S.Actual']!=0) & (df_total['Caducidad'].isna())]

In [110]:
prod_mas_rotacion = df_total.sort_values('Rotación', ascending = False)

In [111]:
with pd.ExcelWriter('reportes_inv_total.xlsx', engine='openpyxl') as writer:
    df_total_sin_caducidad.to_excel(writer, sheet_name='Prod sin caducidad', index=False)
    prod_mas_rotacion.to_excel(writer, sheet_name='Mas rotacion', index=False)

In [115]:
df.columns
df[['Código', 'Descripción', 'Familia', 'Situación', 'S.Actual','S.Minimo', 'S.Maximo', 'Uds.Vendidas', 'Tot.Venta']].sort_values('Uds.Vendidas', ascending=False)

,Código,Descripción,Familia,Situación,S.Actual,S.Minimo,S.Maximo,Uds.Vendidas,Tot.Venta
28908,756029.6,IBUPROFENO 400 RAPID,ESPECIALIDAD,NaN,28,0,0,170.0,965.60
9740,660261.4,PARACETAMOL STADA EFG 1 G 40 COMPRIMIDOS,ESPECIALIDAD,NaN,16,1,3,146.0,365.00
12046,731095.2,PARACETAMOL STADAPHARM EFG 1 G 10 COMPRIMIDOS,ESPECIALIDAD,NaN,18,0,4,123.0,492.00
28,1021.0,KLEENEX BOLSILLO INTERHAPOTEK,BOTIQUIN,NaN,218,0,0,115.0,57.50
24477,692442.6,OMEPRAZOL STADA EFG 20 MG 28 CAPSULAS GASTRORRES,ESPECIALIDAD,NaN,9,2,8,96.0,232.32
...,...,...,...,...,...,...,...,...,...
29558,182252.9,AIRBIOTIC VITEX COMPLEX 60 TABLETS,DIETETICA Y HERBORISTERIA,NaN,0,0,0,NaN,NaN
29641,316494.8,INTERAPOTHEK JABON DE MANOS DE SEDA 300 ML,CORPORAL,NaN,0,0,0,NaN,NaN
29643,326637.6,AVENE COLD CREAM AL AGUA TERMAL 40 ML,COSMÉTICA,NaN,0,0,0,NaN,NaN
29682,650283.9,HALOPERIDOL ESTEVE 2 MG/ML GOTAS ORALES SOLUCION,ESPECIALIDAD,****,1,0,1,NaN,NaN
29686,654127.2,EBASTINA CINFA EFG 20 MG 20 COMPRIMIDOS RECUBIER,ESPECIALIDAD,NaN,0,0,0,NaN,NaN